[package]
name = "sdkwork-provider-adapter-alicloud"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
[lib]
name = "sdkwork_provider_adapter_alicloud"

[dependencies]
sdkwork-cloudrouter-provider-adapter-contract.workspace = true
sdkwork-cloudrouter-provider-adapter.workspace = true
hex.workspace = true
hmac.workspace = true
hyper.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
