import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from 'react-i18next';
export function ConfirmDialog({ title, description, children, confirmLabel = 'Confirm', confirmDisabled = false, cancelLabel = 'Cancel', isBusy = false, tone = 'default', icon, closeOnClickOutside = true, onConfirm, onCancel, }) {
    const { t } = useTranslation();
    const confirmClass = tone === 'danger'
        ? 'bg-red-600 text-white hover:bg-red-700 focus:ring-red-500'
        : 'bg-slate-900 text-white hover:bg-slate-800 focus:ring-slate-500 dark:bg-white dark:text-slate-950 dark:hover:bg-slate-200';
    return (_jsx("div", { className: "fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/50 px-4 backdrop-blur-sm", onPointerDown: (event) => {
            if (closeOnClickOutside && event.target === event.currentTarget) {
                onCancel();
            }
        }, children: _jsxs("div", { role: "alertdialog", "aria-modal": "true", "aria-labelledby": "confirm-dialog-title", "aria-describedby": "confirm-dialog-description", className: "w-full max-w-md rounded-xl border border-slate-200 bg-white p-5 shadow-2xl dark:border-white/10 dark:bg-[#1a1a1a]", children: [_jsxs("div", { className: "flex gap-3", children: [icon ? (_jsx("div", { className: "mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-red-50 text-red-600 dark:bg-red-500/10 dark:text-red-300", children: icon })) : null, _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("h3", { id: "confirm-dialog-title", className: "text-base font-bold text-slate-900 dark:text-white", children: title }), _jsx("p", { id: "confirm-dialog-description", className: "mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300", children: description }), children ? _jsx("div", { className: "mt-3", children: children }) : null] })] }), _jsxs("div", { className: "mt-5 flex justify-end gap-3", children: [_jsx("button", { type: "button", onClick: onCancel, disabled: isBusy, className: "rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 transition-colors hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-60 dark:border-white/10 dark:text-slate-200 dark:hover:bg-white/5", children: cancelLabel }), _jsx("button", { type: "button", onClick: onConfirm, disabled: isBusy || confirmDisabled, "aria-busy": isBusy, className: `rounded-lg px-4 py-2 text-sm font-bold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-60 dark:focus-visible:ring-offset-[#1a1a1a] ${confirmClass}`, children: isBusy ? t('common.actions.deleting') : confirmLabel })] })] }) }));
}
//# sourceMappingURL=ConfirmDialog.js.map