//! Generated gateway bootstrap for sdkwork-clawrouter.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::{body::Body, extract::State, http::Request, response::Response, Router};
use tower::ServiceExt;

pub struct ApiAssembly {
    pub router: Router,
}

#[derive(Clone)]
struct ApplicationRouters {
    app: Router,
    backend: Router,
}

pub fn assemble_api_router() -> ApiAssembly {
    let routers = ApplicationRouters {
        app: sdkwork_routes_clawrouter_app_api::gateway_mount(),
        backend: sdkwork_routes_clawrouter_backend_api::gateway_mount(),
    };
    let router = Router::new()
        .fallback(dispatch_application_request)
        .with_state(routers);
    ApiAssembly { router }
}

async fn dispatch_application_request(
    State(routers): State<ApplicationRouters>,
    request: Request<Body>,
) -> Response {
    let router = if is_backend_path(request.uri().path()) {
        routers.backend
    } else {
        routers.app
    };

    match router.oneshot(request).await {
        Ok(response) => response,
        Err(error) => match error {},
    }
}

fn is_backend_path(path: &str) -> bool {
    path == "/backend" || path.starts_with("/backend/")
}

#[cfg(test)]
mod tests {
    use axum::{
        body::Body,
        http::{Request, StatusCode},
    };
    use tower::ServiceExt;

    use super::assemble_api_router;

    #[tokio::test]
    async fn application_assembly_dispatches_overlapping_full_routers_by_surface() {
        let router = assemble_api_router().router;

        let app_response = router
            .clone()
            .oneshot(get("/app/v3/api/openapi.json"))
            .await
            .expect("app router response");
        assert_eq!(StatusCode::OK, app_response.status());

        let backend_response = router
            .clone()
            .oneshot(get("/backend/v3/api/openapi.json"))
            .await
            .expect("backend router response");
        assert_eq!(StatusCode::OK, backend_response.status());

        let payment_schema_response = router
            .oneshot(get("/payments/v3/openapi.json"))
            .await
            .expect("payment schema response");
        assert_eq!(StatusCode::NOT_FOUND, payment_schema_response.status());
    }

    fn get(path: &str) -> Request<Body> {
        Request::builder()
            .uri(path)
            .body(Body::empty())
            .expect("request")
    }
}
