//! Commerce capability database bootstrap composition.
//!
//! Invoice schema authority lives in `sdkwork-invoice-database-bootstrap`.
//! Claw Router standalone mode composes the appbase commerce tables required by
//! the local stores here so list/search paths start from a complete schema.

use sdkwork_invoice_database_bootstrap::invoice_module_table_names;
use std::collections::BTreeMap;

#[derive(Debug, Clone)]
pub struct CommerceRechargePackageSeed {
    pub status: &'static str,
    pub currency_code: &'static str,
    pub price_amount: &'static str,
    pub bonus_points: i64,
    pub sort_weight: i32,
    pub external_id: i64,
    pub package_no: &'static str,
    pub name: &'static str,
}

#[derive(Debug, Clone)]
pub struct CommerceRechargeSettingsSeed {
    pub rule_no: &'static str,
    pub base_currency_code: &'static str,
    pub currency_to_cny_rates: BTreeMap<&'static str, &'static str>,
    pub source_asset_type: &'static str,
    pub target_asset_type: &'static str,
    pub rate: &'static str,
}

pub fn commerce_recharge_package_seeds() -> Vec<CommerceRechargePackageSeed> {
    vec![
        CommerceRechargePackageSeed {
            status: "active",
            currency_code: "CNY",
            price_amount: "5.00",
            bonus_points: 0,
            sort_weight: 1,
            external_id: 1,
            package_no: "bootstrap-admin-recharge-1",
            name: "CNY 5 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "active",
            currency_code: "CNY",
            price_amount: "10.00",
            bonus_points: 0,
            sort_weight: 2,
            external_id: 2,
            package_no: "bootstrap-admin-recharge-2",
            name: "CNY 10 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "active",
            currency_code: "CNY",
            price_amount: "20.00",
            bonus_points: 0,
            sort_weight: 3,
            external_id: 3,
            package_no: "bootstrap-admin-recharge-3",
            name: "CNY 20 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "active",
            currency_code: "CNY",
            price_amount: "30.00",
            bonus_points: 0,
            sort_weight: 4,
            external_id: 4,
            package_no: "bootstrap-admin-recharge-4",
            name: "CNY 30 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "active",
            currency_code: "CNY",
            price_amount: "50.00",
            bonus_points: 0,
            sort_weight: 5,
            external_id: 5,
            package_no: "bootstrap-admin-recharge-5",
            name: "CNY 50 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "active",
            currency_code: "CNY",
            price_amount: "100.00",
            bonus_points: 0,
            sort_weight: 6,
            external_id: 6,
            package_no: "bootstrap-admin-recharge-6",
            name: "CNY 100 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "active",
            currency_code: "CNY",
            price_amount: "200.00",
            bonus_points: 0,
            sort_weight: 7,
            external_id: 7,
            package_no: "bootstrap-admin-recharge-7",
            name: "CNY 200 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "active",
            currency_code: "CNY",
            price_amount: "500.00",
            bonus_points: 0,
            sort_weight: 8,
            external_id: 8,
            package_no: "bootstrap-admin-recharge-8",
            name: "CNY 500 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "active",
            currency_code: "CNY",
            price_amount: "1000.00",
            bonus_points: 0,
            sort_weight: 9,
            external_id: 9,
            package_no: "bootstrap-admin-recharge-9",
            name: "CNY 1000 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "inactive",
            currency_code: "USD",
            price_amount: "1.00",
            bonus_points: 0,
            sort_weight: 10,
            external_id: 10,
            package_no: "bootstrap-admin-recharge-10",
            name: "USD 1 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "inactive",
            currency_code: "USD",
            price_amount: "2.00",
            bonus_points: 0,
            sort_weight: 11,
            external_id: 11,
            package_no: "bootstrap-admin-recharge-11",
            name: "USD 2 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "inactive",
            currency_code: "USD",
            price_amount: "5.00",
            bonus_points: 0,
            sort_weight: 12,
            external_id: 12,
            package_no: "bootstrap-admin-recharge-12",
            name: "USD 5 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "inactive",
            currency_code: "USD",
            price_amount: "10.00",
            bonus_points: 0,
            sort_weight: 13,
            external_id: 13,
            package_no: "bootstrap-admin-recharge-13",
            name: "USD 10 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "inactive",
            currency_code: "USD",
            price_amount: "20.00",
            bonus_points: 0,
            sort_weight: 14,
            external_id: 14,
            package_no: "bootstrap-admin-recharge-14",
            name: "USD 20 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "inactive",
            currency_code: "USD",
            price_amount: "50.00",
            bonus_points: 0,
            sort_weight: 15,
            external_id: 15,
            package_no: "bootstrap-admin-recharge-15",
            name: "USD 50 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "inactive",
            currency_code: "USD",
            price_amount: "100.00",
            bonus_points: 0,
            sort_weight: 16,
            external_id: 16,
            package_no: "bootstrap-admin-recharge-16",
            name: "USD 100 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "inactive",
            currency_code: "USD",
            price_amount: "200.00",
            bonus_points: 0,
            sort_weight: 17,
            external_id: 17,
            package_no: "bootstrap-admin-recharge-17",
            name: "USD 200 points recharge",
        },
        CommerceRechargePackageSeed {
            status: "inactive",
            currency_code: "USD",
            price_amount: "500.00",
            bonus_points: 0,
            sort_weight: 18,
            external_id: 18,
            package_no: "bootstrap-admin-recharge-18",
            name: "USD 500 points recharge",
        },
    ]
}

pub fn commerce_recharge_settings_seeds() -> Vec<CommerceRechargeSettingsSeed> {
    vec![CommerceRechargeSettingsSeed {
        rule_no: "CASH_TO_POINTS",
        base_currency_code: "CNY",
        currency_to_cny_rates: BTreeMap::from([("CNY", "1"), ("USD", "7")]),
        source_asset_type: "cash",
        target_asset_type: "points",
        rate: "10",
    }]
}

pub fn commerce_database_tables() -> Vec<&'static str> {
    let mut tables = vec![
        "commerce_product_category",
        "commerce_product_attribute",
        "commerce_product_attribute_value",
        "commerce_product_category_attribute",
        "commerce_product_spu",
        "commerce_product_spu_category",
        "commerce_product_sku",
        "commerce_product_sku_attribute",
        "commerce_product_media",
        "commerce_price_list",
        "commerce_price_list_item",
        "commerce_recharge_package",
        "commerce_exchange_rule",
        "promotion_offer",
        "promotion_offer_version",
        "promotion_coupon_stock",
        "promotion_code",
        "promotion_user_coupon",
        "promotion_discount_application",
        "promotion_coupon_ledger_entry",
        "commerce_account",
        "commerce_account_ledger_entry",
        "commerce_settlement",
        "commerce_statement",
        "commerce_order",
        "commerce_order_item",
        "commerce_order_amount_breakdown",
        "commerce_order_event",
        "commerce_payment_intent",
        "commerce_payment_attempt",
        "commerce_payment_route_decision",
        "commerce_payment_operation_attempt",
        "commerce_payment_webhook_event",
        "commerce_payment_webhook_delivery",
        "commerce_payment_statement",
        "commerce_payment_statement_item",
        "commerce_payment_reconciliation_run",
        "commerce_payment_reconciliation_item",
        "commerce_refund",
        "commerce_refund_attempt",
        "commerce_refund_item",
        "commerce_refund_event",
        "commerce_payment_provider",
        "commerce_payment_provider_account",
        "commerce_payment_method",
        "commerce_payment_channel",
        "commerce_payment_route_rule",
        "commerce_inventory_stock",
        "commerce_inventory_reservation",
        "commerce_inventory_movement",
        "commerce_fulfillment_order",
        "commerce_shipment",
        "commerce_shipment_tracking_event",
    ];
    tables.extend(invoice_module_table_names());
    tables
}
