[package]
name = "sdkwork-provider-adapter-alicloud"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
sdkwork-claw-provider-adapter-contract.workspace = true
sdkwork-claw-provider-adapter.workspace = true
hex.workspace = true
hmac.workspace = true
hyper.workspace = true
serde_json.workspace = true
sha2.workspace = true
