[package]
name = "sdkwork-api-cloudrouter-assembly"
edition.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-cloudrouter application HTTP plane."

[lib]
name = "sdkwork_api_cloudrouter_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
anyhow.workspace = true
sdkwork-cloudrouter-http.workspace = true
sdkwork-cloudrouter-edge-runtime.workspace = true
sdkwork-web-contract.workspace = true
sdkwork-iam-database-host.workspace = true
sdkwork-iam-embedded-application-bootstrap.workspace = true
sdkwork-routes-iam-app-api.workspace = true
sdkwork_account_repository_sqlx.workspace = true
sdkwork_account_service_host.workspace = true
tracing.workspace = true
tower.workspace = true
serde_json.workspace = true
sdkwork-routes-agent-open-api.workspace = true
sdkwork-routes-audio-open-api.workspace = true
sdkwork-routes-cloudrouter-app-api.workspace = true
sdkwork-routes-cloudrouter-backend-api.workspace = true
sdkwork-routes-cloudrouter-drive-open-api.workspace = true
sdkwork-routes-cloudrouter-knowledgebase-open-api.workspace = true
sdkwork-routes-cloudrouter-llm-open-api.workspace = true
sdkwork-routes-cloudrouter-memory-open-api.workspace = true
sdkwork-routes-iaas-open-api.workspace = true
sdkwork-routes-image-open-api.workspace = true
sdkwork-routes-paas-open-api.workspace = true
sdkwork-routes-payment-open-api.workspace = true
sdkwork-routes-video-open-api.workspace = true
