import type { OpenAiResponseInputTokensDetails } from './open-ai-response-input-tokens-details';
import type { OpenAiResponseOutputTokensDetails } from './open-ai-response-output-tokens-details';
import type { ProviderJsonValue } from './provider-json-value';

/** OpenAI-compatible open ai response usage schema exposed by Claw Router. */
export interface OpenAiResponseUsage {
  /** Number of input tokens billed for the response. */
  input_tokens: number;
  /** Input tokens details field on the open ai response usage, using the open ai response input tokens details module. */
  input_tokens_details?: OpenAiResponseInputTokensDetails;
  /** Number of output tokens generated by the response. */
  output_tokens: number;
  /** Output tokens details field on the open ai response usage, using the open ai response output tokens details module. */
  output_tokens_details?: OpenAiResponseOutputTokensDetails;
  /** Total input and output token count. */
  total_tokens: number;
}
