[package]
name = "sdkwork-cloudrouter-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
[lib]
name = "sdkwork_cloudrouter_config"

[dependencies]
serde.workspace = true
serde_json.workspace = true
sdkwork-cloudrouter-provider-adapter-contract.workspace = true
sdkwork-cloudrouter-provider-adapter-registry.workspace = true
sdkwork-database-config.workspace = true
toml.workspace = true
url.workspace = true

[lints]
workspace = true
