import type { TFunction } from 'i18next';
import { getSdkworkDriveAppSdkClient } from '@sdkwork/cloudroutes-pc-commons/sdk-clients';
import type {
  SandboxCapabilities,
  SandboxExplorerLabels,
  SandboxExplorerPort,
} from '@sdkwork/drive-pc-sandbox-explorer';
import {
  createDriveSandboxExplorerSdkPort,
  type DriveSandboxExplorerSdkClient,
} from '@sdkwork/drive-pc-sandbox-explorer-sdk-adapter';

export interface BucketExplorerTarget {
  readonly id: string;
  readonly bucketName: string;
}

const BUCKET_ROOT_CAPABILITIES: SandboxCapabilities = {
  browse: true,
  createFile: true,
  createDirectory: true,
  deleteEntry: true,
  moveEntry: true,
  readFile: true,
  selectDirectory: false,
  writeFile: true,
};

/**
 * 以存储桶作为沙箱根的文件浏览端口。条目/文件/目录/内容 CRUD 全部委托给
 * drive app SDK 的 sandbox 接口（与 cloudrouter 同域部署）；`listSandboxes`
 * 固定返回当前存储桶作为唯一根，其余方法透传真实 SDK 客户端。
 */
export function createBucketExplorerPort(bucket: BucketExplorerTarget): SandboxExplorerPort {
  const client = getSdkworkDriveAppSdkClient();
  const sandboxClient: DriveSandboxExplorerSdkClient = {
    ...client,
    drive: {
      ...client.drive,
      sandboxes: {
        list: async () => ({
          items: [{
            id: bucket.id,
            displayName: bucket.bucketName,
            rootEntryId: bucket.id,
            capabilities: BUCKET_ROOT_CAPABILITIES,
          }],
          pageInfo: { mode: 'offset', totalItems: '1', totalPages: 1 },
        }),
      },
    },
  };
  return createDriveSandboxExplorerSdkPort({ client: sandboxClient });
}

/** 存储桶文件浏览器的界面文案（中文/英文，通过 i18n 注入）。 */
export function bucketExplorerLabels(t: TFunction): SandboxExplorerLabels {
  return {
    sandboxFileExplorer: t('admin.storage.explorer.sandboxFileExplorer', 'Sandbox file explorer'),
    back: t('admin.storage.explorer.back', 'Back'),
    forward: t('admin.storage.explorer.forward', 'Forward'),
    parentDirectory: t('admin.storage.explorer.parentDirectory', 'Parent directory'),
    refresh: t('admin.storage.explorer.refresh', 'Refresh'),
    navigationHistory: t('admin.storage.explorer.navigationHistory', 'Navigation history'),
    currentLogicalPath: t('admin.storage.explorer.currentLogicalPath', 'Current logical path'),
    sandboxAbsolutePath: t('admin.storage.explorer.sandboxAbsolutePath', 'Sandbox absolute path'),
    noSandboxPath: t('admin.storage.explorer.noSandboxPath', 'No sandbox path available'),
    copyPath: t('admin.storage.explorer.copyPath', 'Copy path'),
    pathCopied: t('admin.storage.explorer.pathCopied', 'Path copied'),
    copyFullPath: t('admin.storage.explorer.copyFullPath', 'Copy full sandbox path'),
    pathCopiedAnnouncement: t('admin.storage.explorer.pathCopiedAnnouncement', 'Sandbox path copied to clipboard.'),
    filterLoadedItems: t('admin.storage.explorer.filterLoadedItems', 'Filter loaded items'),
    searchPlaceholder: t('admin.storage.explorer.searchPlaceholder', 'Filter loaded items in {name}'),
    clearSearch: t('admin.storage.explorer.clearSearch', 'Clear search'),
    newFolder: t('admin.storage.explorer.newFolder', 'New folder'),
    newFile: t('admin.storage.explorer.newFile', 'New file'),
    uploadFile: t('admin.storage.explorer.uploadFile', 'Upload file'),
    uploadingFiles: t('admin.storage.explorer.uploadingFiles', 'Uploading {current}/{total}…'),
    fileTooLarge: t('admin.storage.explorer.fileTooLarge', 'File exceeds the 4 MB sandbox limit.'),
    uploadError: t('admin.storage.explorer.uploadError', 'Unable to upload the file.'),
    folderName: t('admin.storage.explorer.folderName', 'Folder name'),
    fileName: t('admin.storage.explorer.fileName', 'File name'),
    createFolder: t('admin.storage.explorer.createFolder', 'Create folder'),
    createFile: t('admin.storage.explorer.createFile', 'Create file'),
    cancelFileCreation: t('admin.storage.explorer.cancelFileCreation', 'Cancel file creation'),
    rename: t('admin.storage.explorer.rename', 'Rename'),
    delete: t('admin.storage.explorer.delete', 'Delete'),
    sort: t('admin.storage.explorer.sort', 'Sort'),
    sortAscending: t('admin.storage.explorer.sortAscending', 'Sort ascending'),
    sortDescending: t('admin.storage.explorer.sortDescending', 'Sort descending'),
    switchToGridView: t('admin.storage.explorer.switchToGridView', 'Switch to grid view'),
    switchToDetailsView: t('admin.storage.explorer.switchToDetailsView', 'Switch to details view'),
    view: t('admin.storage.explorer.view', 'View'),
    moreOptions: t('admin.storage.explorer.moreOptions', 'More options'),
    gridView: t('admin.storage.explorer.gridView', 'Grid view'),
    detailsView: t('admin.storage.explorer.detailsView', 'Details view'),
    details: t('admin.storage.explorer.details', 'Details'),
    hideDetailsPane: t('admin.storage.explorer.hideDetailsPane', 'Hide details pane'),
    showDetailsPane: t('admin.storage.explorer.showDetailsPane', 'Show details pane'),
    reload: t('admin.storage.explorer.reload', 'Reload'),
    retry: t('admin.storage.explorer.retry', 'Retry'),
    dismiss: t('admin.storage.explorer.dismiss', 'Dismiss'),
    sandboxNavigation: t('admin.storage.explorer.sandboxNavigation', 'Sandbox navigation'),
    sandboxes: t('admin.storage.explorer.sandboxes', 'Sandboxes'),
    sandbox: t('admin.storage.explorer.sandbox', 'Sandbox'),
    availableSandboxes: t('admin.storage.explorer.availableSandboxes', 'Available sandboxes'),
    openSandbox: t('admin.storage.explorer.openSandbox', 'Open sandbox {name}'),
    moreSandboxes: t('admin.storage.explorer.moreSandboxes', 'More sandboxes'),
    loading: t('admin.storage.explorer.loading', 'Loading'),
    loadingFolder: t('admin.storage.explorer.loadingFolder', 'Loading folder…'),
    loadingFile: t('admin.storage.explorer.loadingFile', 'Loading file…'),
    noAccessibleSandboxes: t('admin.storage.explorer.noAccessibleSandboxes', 'No accessible sandboxes.'),
    folderEmpty: t('admin.storage.explorer.folderEmpty', 'This folder is empty.'),
    noSearchMatches: t('admin.storage.explorer.noSearchMatches', 'No items match your search.'),
    directoryItems: t('admin.storage.explorer.directoryItems', 'Directory items'),
    itemDetails: t('admin.storage.explorer.itemDetails', 'Item details'),
    nameColumn: t('admin.storage.explorer.nameColumn', 'Name'),
    typeColumn: t('admin.storage.explorer.typeColumn', 'Type'),
    locationColumn: t('admin.storage.explorer.locationColumn', 'Location'),
    loadMore: t('admin.storage.explorer.loadMore', 'Load more'),
    loadMoreItems: t('admin.storage.explorer.loadMoreItems', 'Load more items'),
    loadingMoreItems: t('admin.storage.explorer.loadingMoreItems', 'Loading more items…'),
    moreItemsAvailable: t('admin.storage.explorer.moreItemsAvailable', 'More items available'),
    allItemsLoaded: t('admin.storage.explorer.allItemsLoaded', 'All items loaded'),
    itemsLoadedOne: t('admin.storage.explorer.itemsLoadedOne', '{count} item loaded'),
    itemsLoadedMany: t('admin.storage.explorer.itemsLoadedMany', '{count} items loaded'),
    filteredFrom: t('admin.storage.explorer.filteredFrom', 'Filtered from {count}'),
    filtering: t('admin.storage.explorer.filtering', 'Filtering…'),
    refreshing: t('admin.storage.explorer.refreshing', 'Refreshing…'),
    noSandboxSelected: t('admin.storage.explorer.noSandboxSelected', 'No sandbox selected'),
    selectDirectory: t('admin.storage.explorer.selectDirectory', 'Select directory'),
    entryActions: t('admin.storage.explorer.entryActions', '{name} actions'),
    currentFolderActions: t('admin.storage.explorer.currentFolderActions', 'Current folder actions'),
    open: t('admin.storage.explorer.open', 'Open'),
    openFile: t('admin.storage.explorer.openFile', 'Open file'),
    copyAsPath: t('admin.storage.explorer.copyAsPath', 'Copy as path'),
    copyPathname: t('admin.storage.explorer.copyPathname', 'Copy pathname'),
    copyLocation: t('admin.storage.explorer.copyLocation', 'Copy Location'),
    copyCurrentPath: t('admin.storage.explorer.copyCurrentPath', 'Copy current path'),
    moveTo: t('admin.storage.explorer.moveTo', 'Move to…'),
    getInfo: t('admin.storage.explorer.getInfo', 'Get Info'),
    properties: t('admin.storage.explorer.properties', 'Properties'),
    info: t('admin.storage.explorer.info', 'Info'),
    deletePermanently: t('admin.storage.explorer.deletePermanently', 'Delete permanently'),
    selectItemDetails: t('admin.storage.explorer.selectItemDetails', 'Select an item to view its details.'),
    editFile: t('admin.storage.explorer.editFile', 'Edit {name}'),
    closeFile: t('admin.storage.explorer.closeFile', 'Close file'),
    fileContent: t('admin.storage.explorer.fileContent', 'File content'),
    binaryPreview: t('admin.storage.explorer.binaryPreview', 'Binary preview'),
    bytes: t('admin.storage.explorer.bytes', '{count} bytes'),
    base64ReadOnly: t('admin.storage.explorer.base64ReadOnly', 'Base64-encoded read-only content'),
    sha256: t('admin.storage.explorer.sha256', 'SHA-256 {digest}'),
    utf8Text: t('admin.storage.explorer.utf8Text', 'UTF-8 text'),
    close: t('admin.storage.explorer.close', 'Close'),
    save: t('admin.storage.explorer.save', 'Save'),
    name: t('admin.storage.explorer.name', 'Name'),
    kind: t('admin.storage.explorer.kind', 'Kind'),
    type: t('admin.storage.explorer.type', 'Type'),
    location: t('admin.storage.explorer.location', 'Location'),
    logicalPath: t('admin.storage.explorer.logicalPath', 'Logical path'),
    revision: t('admin.storage.explorer.revision', 'Revision'),
    ok: t('admin.storage.explorer.ok', 'OK'),
    newName: t('admin.storage.explorer.newName', 'New name'),
    renameDialogTitle: t('admin.storage.explorer.renameDialogTitle', 'Rename {name}'),
    moveDialogTitle: t('admin.storage.explorer.moveDialogTitle', 'Move {name}'),
    deleteDialogTitle: t('admin.storage.explorer.deleteDialogTitle', 'Delete {name}'),
    destinationFolderPath: t('admin.storage.explorer.destinationFolderPath', 'Destination folder path'),
    emptyForSandboxRoot: t('admin.storage.explorer.emptyForSandboxRoot', 'Empty for sandbox root'),
    moveHint: t('admin.storage.explorer.moveHint', 'Use a sandbox-relative path with forward slashes.'),
    move: t('admin.storage.explorer.move', 'Move'),
    cancel: t('admin.storage.explorer.cancel', 'Cancel'),
    deleteConfirm: t('admin.storage.explorer.deleteConfirm', 'This permanently deletes the {kind}. This action cannot be undone.'),
    fileKindNoun: t('admin.storage.explorer.fileKindNoun', 'file'),
    directoryKindNoun: t('admin.storage.explorer.directoryKindNoun', 'directory'),
    fileFolderType: t('admin.storage.explorer.fileFolderType', 'File folder'),
    fileTypeExtension: t('admin.storage.explorer.fileTypeExtension', '{extension} file'),
    fileTypeGeneric: t('admin.storage.explorer.fileTypeGeneric', 'File'),
    sandboxFolderType: t('admin.storage.explorer.sandboxFolderType', 'Sandbox folder'),
    loadDirectoryError: t('admin.storage.explorer.loadDirectoryError', 'Unable to load the sandbox directory.'),
    loadSandboxesError: t('admin.storage.explorer.loadSandboxesError', 'Unable to load available sandboxes.'),
    loadMoreSandboxesError: t('admin.storage.explorer.loadMoreSandboxesError', 'Unable to load more sandboxes.'),
    loadMoreEntriesError: t('admin.storage.explorer.loadMoreEntriesError', 'Unable to load more directory entries.'),
    createDirectoryError: t('admin.storage.explorer.createDirectoryError', 'Unable to create the directory.'),
    createFileError: t('admin.storage.explorer.createFileError', 'Unable to create the file.'),
    readFileError: t('admin.storage.explorer.readFileError', 'Unable to read the file.'),
    saveFileError: t('admin.storage.explorer.saveFileError', 'Unable to save the file.'),
    renameEntryError: t('admin.storage.explorer.renameEntryError', 'Unable to rename the entry.'),
    moveEntryError: t('admin.storage.explorer.moveEntryError', 'Unable to move the entry.'),
    deleteEntryError: t('admin.storage.explorer.deleteEntryError', 'Unable to delete the entry.'),
    copyPathError: t('admin.storage.explorer.copyPathError', 'Unable to copy the sandbox path.'),
  };
}
