from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

from tools.schema_registry_loader import load_schema_registry


ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / "docs" / "schema-registry" / "sdkwork-clawrouter.tables.yaml"
OUTPUT_PATH = ROOT / "docs" / "schema-registry" / "table-catalog.md"
REGISTRY_DISPLAY_PATH = "docs/schema-registry/sdkwork-clawrouter.tables.yaml"


TABLE_DESCRIPTIONS = {
    "ai_upstream_supplier": "Upstream supplier identity and supplier classification.",
    "ai_upstream_supplier_endpoint": "Supplier Base URL endpoint, region, priority, and routing weight.",
    "ai_upstream_supplier_endpoint_health_state": "Current health and latency state for a supplier endpoint.",
    "ai_upstream_supplier_auth_method": "Authentication methods supported by a supplier, with runtime injection policy.",
    "ai_upstream_supplier_resource": "Resource and resource-group capabilities exposed by a supplier.",
    "ai_upstream_account": "Tenant-scoped upstream account linked to one supplier and authentication method.",
    "ai_upstream_account_credential": "Encrypted, versioned credential material for an upstream account.",
    "ai_upstream_account_health_state": "Current health, usage, and failure state for an upstream account.",
    "ai_upstream_account_group": "Routing and settlement group for one or more upstream accounts.",
    "ai_upstream_account_group_member": "Weighted membership of upstream accounts in an account group.",
    "ai_upstream_account_group_resource": "Resource grants and denials applied to an account group.",
    "ai_upstream_account_group_metric_snapshot": "Rebuildable capacity and usage projection for an account group.",
    "ai_upstream_object_route": "Runtime object-storage route resolved through an upstream account.",
    "iam_gateway_api_key_account_group": "Authorized account-group binding for a gateway API key.",
    "ai_request_trace": "Append-only request execution trace for routing and operations.",
    "ai_usage": "Idempotent billable usage fact used for settlement and reconciliation.",
}


def render_table_catalog(registry_path: Path = REGISTRY_PATH) -> str:
    registry = load_schema_registry(registry_path)
    tables = sorted(
        (
            table
            for table in registry.get("tables", [])
            if isinstance(table, dict) and isinstance(table.get("table"), str)
        ),
        key=lambda table: (str(table.get("domain") or "unknown"), table["table"]),
    )
    domain_counts = Counter(str(table.get("domain") or "unknown") for table in tables)
    generated_count = sum(
        1 for table in tables if table.get("generated_by_this_project") is not False
    )

    lines = [
        "# Claw Router Database Table Catalog",
        "",
        f"Generated from `{REGISTRY_DISPLAY_PATH}`. Do not edit this file manually.",
        "",
        f"- Table count: {len(tables)}",
        f"- Project-generated table count: {generated_count}",
        "- Server authority: PostgreSQL",
        "",
        "## Domain Summary",
        "",
        "| Domain | Tables |",
        "| --- | ---: |",
    ]
    for domain, count in sorted(domain_counts.items()):
        lines.append(f"| `{escape_cell(domain)}` | {count} |")

    by_domain: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for table in tables:
        by_domain[str(table.get("domain") or "unknown")].append(table)

    for domain, domain_tables in sorted(by_domain.items()):
        lines.extend(
            [
                "",
                f"## {domain}",
                "",
                "| Table | Purpose | Profile | Write owner | Generated here |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for table in domain_tables:
            table_name = table["table"]
            profile = str(table.get("profile") or "")
            owner = str(table.get("write_owner") or "")
            generated = "yes" if table.get("generated_by_this_project") is not False else "no"
            lines.append(
                f"| `{table_name}` | {escape_cell(describe_table(table))} | "
                f"`{escape_cell(profile)}` | `{escape_cell(owner)}` | {generated} |"
            )

    return "\n".join(lines).rstrip() + "\n"


def describe_table(table: dict[str, Any]) -> str:
    table_name = table["table"]
    direct_description = TABLE_DESCRIPTIONS.get(table_name)
    if direct_description is not None:
        return direct_description

    subject = table_name.replace("_", " ")
    profile = str(table.get("profile") or "table").replace("_", " ")
    if table.get("generated_by_this_project") is False:
        return f"Referenced {profile} for {subject}; owned by a dependency registry."
    return f"{profile.capitalize()} for {subject}."


def escape_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def main() -> int:
    OUTPUT_PATH.write_text(render_table_catalog(), encoding="utf-8")
    print(f"Wrote table catalog to {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
